
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;        
using UnityEngine.UI;
using System;
using DG.Tweening;
using GameCore.Stats;
using GameCore.CustomComponent.Role;
using GameCore;

namespace Abyss.Stat
{
    /// <summary>
    /// 每层流血为下次攻击提供1点额外伤害，并移除所有流血层数。
    /// </summary>
    [GameBuff(30003)]
    public class Buff_Bleeding : BaseGameBuff
    {
        public override void OnRoundStart()
        {
            base.OnRoundStart();

        }
        
        public override void OnRoundEnd()
        {
            base.OnRoundEnd();

        }

        public override void OnApply()
        {
            base.OnApply();

        }
        public override void Calculate(ref int originalValue)
        {

        }

        public Buff_Bleeding(BaseRole owner, GameBuffView view) : base(owner, view)
        {
            this.cfg = Entry.Luban.Tables.TbGameBuff.DataMap[30003];
        }
    }
}        
