
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;        
using UnityEngine.UI;
using System;

namespace Abyss.Stat
{
    /// <summary>
    /// 所有buff所生成的对应ID
    /// </summary>  
    public enum EnumGameBuff
    {
        Wounded = 30001,
Weak = 30002,
Bleeding = 30003,
Fragile = 30004,
Mocking = 30005,
DmgControl = 30006,
Unyielding = 30007,

    }
    
}
