
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;        
using UnityEngine.UI;
using System;
using DG.Tweening;
using GameCore.CustomComponent.Role;

namespace Abyss.GameActions
{
    /// <summary>
    /// 消耗你所有手牌，每张被消耗的卡牌获得 [value] 点护甲。
    /// </summary>
    [CardAction(10420)]
    public class Action_ConsumeHandCardGainBlock : BaseGameAction
    {
        public override void Execute(BaseRole self, object targets, int value, DG.Tweening.Sequence sequence)
        {
            //TODO  
        }
    }
}        
