
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;        
using UnityEngine.UI;
using System;
using DG.Tweening;
using GameCore.CustomComponent.Role;

namespace Abyss.GameActions
{
    /// <summary>
    /// 如果目标敌人的生命值小于等于 [value] 点，则将其生命值变为 0。
    /// </summary>
    [CardAction(10220)]
    public class Action_InstantKill : BaseGameAction
    {
        public override void Execute(BaseRole self, object targets, int value, DG.Tweening.Sequence sequence)
        {
            //TODO  
        }
    }
}        
