
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;        
using UnityEngine.UI;
using System;
using DG.Tweening;
using GameCore.CustomComponent.Role;

namespace Abyss.GameActions
{
    /// <summary>
    /// 造成 [value] 点伤害。
    /// </summary>
    [CardAction(10010)]
    public class 
        Action_HarmAndBleed : BaseGameAction
    {
        public override void Execute(BaseRole self, object targets, int value, DG.Tweening.Sequence sequence)
        {
            //TODO  
           var val = self.Stat.QueryNormalAttack( value);
            (targets as BaseRole).AcceptAtkDmg(val);
            // var originalPos = self.transform.position.x;
            // var va =  self.Stat.QueryNormalAttack(value, true);
            // var targetPosX = (targets as BaseRole).transform.position.x;
            // var isRight = self.transform.position.x > targetPosX ? 1 : -1;
            // // sequence.Append(self.transform.DOMoveX(targetPosX + isRight * 0.1f, 0.2f))
            // sequence.Append(self.transform.DOMoveX(targetPosX + isRight * 3f, 0.2f))
            //     .AppendInterval(0.05f)
            //     .AppendCallback(() =>
            //     {
            //         (targets as BaseRole).AcceptAtkDmg(va);
            //
            //     }).AppendInterval(0.1f).Append(self.transform.DOMoveX(originalPos, 0.2f));
        }
    }
}        
