
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;        
using UnityEngine.UI;
using System;
using DG.Tweening;
using GameCore.CustomComponent.Role;

namespace Abyss.GameActions
{
    /// <summary>
    /// 如果你有护甲，造成额外 [value] 点伤害。
    /// </summary>
    [CardAction(10050)]
    public class Action_ExtraHarmIfArmor : BaseGameAction
    {
        public override void Execute(BaseRole self, object targets, int value, DG.Tweening.Sequence sequence)
        {
            //TODO  
        }
    }
}        
