
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.gameCard
{ 
    public enum Operation
    {
        /// <summary>
        /// 不做任何操作
        /// </summary>
        NONE = 0,
        /// <summary>
        /// 选择敌人
        /// </summary>
        SELECT_ENEMY = 1,
    }

} 

