
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class GameMonsterActionPattern : Luban.BeanBase
{
    public GameMonsterActionPattern(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Cards = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Cards[__index0] = __e0;}}
    }

    public static GameMonsterActionPattern DeserializeGameMonsterActionPattern(ByteBuf _buf)
    {
        return new GameMonsterActionPattern(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 输入card表中的卡片id，游戏中会按照顺序每回合触发一张卡片效果，如果一个队列走完了之后会进行循环
    /// </summary>
    public readonly int[] Cards;
   
    public const int __ID__ = 1572007410;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "cards:" + Luban.StringUtil.CollectionToString(Cards) + ","
        + "}";
    }
}

}
