
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.gameMonster
{ 
    public enum monsterType
    {
        /// <summary>
        /// 杂兵
        /// </summary>
        NORMAL = 0,
        /// <summary>
        /// 精英怪
        /// </summary>
        ELITE = 1,
        /// <summary>
        /// BOSS
        /// </summary>
        BOSS = 2,
    }

} 

