
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;

namespace cfg.gameCard
{ 
    [Flags]
    public enum ExtraOperation
    {
        /// <summary>
        /// 普通
        /// </summary>
        NORMAL = 0,
        /// <summary>
        /// 保留
        /// </summary>
        DETAIN = 1,
        /// <summary>
        /// 虚无
        /// </summary>
        ETHEREAL = 2,
        /// <summary>
        /// 固有
        /// </summary>
        INNATE = 4,
        /// <summary>
        /// 消耗
        /// </summary>
        EXHAUST = 8,
        /// <summary>
        /// 唯一
        /// </summary>
        UNIQUE = 16,
    }

} 

