
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class GameMonster : Luban.BeanBase
{
    public GameMonster(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        MaxHp = _buf.ReadInt();
        Type = (gameMonster.monsterType)_buf.ReadInt();
        Desc = _buf.ReadString();
        Res = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Behaviour = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Behaviour[__index0] = __e0;}}
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Relics = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Relics[__index0] = __e0;}}
    }

    public static GameMonster DeserializeGameMonster(ByteBuf _buf)
    {
        return new GameMonster(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 基础生命值
    /// </summary>
    public readonly int MaxHp;
    /// <summary>
    /// NORMAL或ELITE或BOSS
    /// </summary>
    public readonly gameMonster.monsterType Type;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly int Res;
    /// <summary>
    /// 可能的出牌流程（monsterAction.xlsx的ID列）
    /// </summary>
    public readonly int[] Behaviour;
    public readonly int[] Relics;
   
    public const int __ID__ = -1524021400;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "maxHp:" + MaxHp + ","
        + "type:" + Type + ","
        + "desc:" + Desc + ","
        + "res:" + Res + ","
        + "behaviour:" + Luban.StringUtil.CollectionToString(Behaviour) + ","
        + "relics:" + Luban.StringUtil.CollectionToString(Relics) + ","
        + "}";
    }
}

}
