
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class GameRes : Luban.BeanBase
{
    public GameRes(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Path = _buf.ReadString();
    }

    public static GameRes DeserializeGameRes(ByteBuf _buf)
    {
        return new GameRes(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string Path;
   
    public const int __ID__ = 1469034286;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "path:" + Path + ","
        + "}";
    }
}

}
