
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public demo.TbReward TbReward {get; }
    public TbCardModel TbCardModel {get; }
    public TbGameActions TbGameActions {get; }
    public TbGameBuff TbGameBuff {get; }
    public TbGameMonster TbGameMonster {get; }
    public TbGameMonsterActionPattern TbGameMonsterActionPattern {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbReward = new demo.TbReward(loader("demo_tbreward"));
        TbCardModel = new TbCardModel(loader("tbcardmodel"));
        TbGameActions = new TbGameActions(loader("tbgameactions"));
        TbGameBuff = new TbGameBuff(loader("tbgamebuff"));
        TbGameMonster = new TbGameMonster(loader("tbgamemonster"));
        TbGameMonsterActionPattern = new TbGameMonsterActionPattern(loader("tbgamemonsteractionpattern"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbReward.ResolveRef(this);
        TbCardModel.ResolveRef(this);
        TbGameActions.ResolveRef(this);
        TbGameBuff.ResolveRef(this);
        TbGameMonster.ResolveRef(this);
        TbGameMonsterActionPattern.ResolveRef(this);
    }
}

}
