
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGameRelic
{
    private readonly System.Collections.Generic.Dictionary<int, GameRelic> _dataMap;
    private readonly System.Collections.Generic.List<GameRelic> _dataList;
    
    public TbGameRelic(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameRelic>();
        _dataList = new System.Collections.Generic.List<GameRelic>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameRelic _v;
            _v = GameRelic.DeserializeGameRelic(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameRelic> DataMap => _dataMap;
    public System.Collections.Generic.List<GameRelic> DataList => _dataList;

    public GameRelic GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameRelic Get(int key) => _dataMap[key];
    public GameRelic this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

