
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGameRes
{
    private readonly System.Collections.Generic.Dictionary<int, GameRes> _dataMap;
    private readonly System.Collections.Generic.List<GameRes> _dataList;
    
    public TbGameRes(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameRes>();
        _dataList = new System.Collections.Generic.List<GameRes>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameRes _v;
            _v = GameRes.DeserializeGameRes(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameRes> DataMap => _dataMap;
    public System.Collections.Generic.List<GameRes> DataList => _dataList;

    public GameRes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameRes Get(int key) => _dataMap[key];
    public GameRes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

