
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGameActions
{
    private readonly System.Collections.Generic.Dictionary<int, GameActions> _dataMap;
    private readonly System.Collections.Generic.List<GameActions> _dataList;
    
    public TbGameActions(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameActions>();
        _dataList = new System.Collections.Generic.List<GameActions>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameActions _v;
            _v = GameActions.DeserializeGameActions(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameActions> DataMap => _dataMap;
    public System.Collections.Generic.List<GameActions> DataList => _dataList;

    public GameActions GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameActions Get(int key) => _dataMap[key];
    public GameActions this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

