
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGameMonster
{
    private readonly System.Collections.Generic.Dictionary<int, GameMonster> _dataMap;
    private readonly System.Collections.Generic.List<GameMonster> _dataList;
    
    public TbGameMonster(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameMonster>();
        _dataList = new System.Collections.Generic.List<GameMonster>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameMonster _v;
            _v = GameMonster.DeserializeGameMonster(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameMonster> DataMap => _dataMap;
    public System.Collections.Generic.List<GameMonster> DataList => _dataList;

    public GameMonster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameMonster Get(int key) => _dataMap[key];
    public GameMonster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

