
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGameMonsterActionPattern
{
    private readonly System.Collections.Generic.Dictionary<int, GameMonsterActionPattern> _dataMap;
    private readonly System.Collections.Generic.List<GameMonsterActionPattern> _dataList;
    
    public TbGameMonsterActionPattern(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameMonsterActionPattern>();
        _dataList = new System.Collections.Generic.List<GameMonsterActionPattern>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GameMonsterActionPattern _v;
            _v = GameMonsterActionPattern.DeserializeGameMonsterActionPattern(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameMonsterActionPattern> DataMap => _dataMap;
    public System.Collections.Generic.List<GameMonsterActionPattern> DataList => _dataList;

    public GameMonsterActionPattern GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameMonsterActionPattern Get(int key) => _dataMap[key];
    public GameMonsterActionPattern this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

