// Generated by dojo-bindgen on Fri, 21 Jun 2024 11:07:27 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


// Model definition for `abyss_x::models::card::Card` model
public class Card : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("slot_1")]
    public ulong slot_1;

    [ModelField("slot_2")]
    public ulong slot_2;

    // Start is called before the first frame update
    void Start() {
        
    }

    // Update is called once per frame
    void Update() {
        
    }
}
        