// Generated by dojo-bindgen on Tue, 18 Jun 2024 07:35:41 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using System.Numerics;

// Type definition for `core::integer::u256` struct
[Serializable]
public struct U256 {
    public BigInteger low;
    public BigInteger high;
}


// Model definition for `abyss_x::models::card::Card` model
public class Card : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("cards")]
    public U256 cards;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        