// Generated by dojo-bindgen on Tue, 18 Jun 2024 07:35:41 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Dojo.Torii;
using UnityEngine;
using Enum = Dojo.Starknet.Enum;

// Type definition for `abyss_x::utils::constant::EventCode` enum
public abstract record EventCode() : Enum {
    public record None() : EventCode;
    public record Login() : EventCode;
    public record SetNickName() : EventCode;
    public record StartGame() : EventCode;
    public record GiveUpGame() : EventCode;
    public record CheckBattleResult() : EventCode;
    public record ChooseEventBonus() : EventCode;
    public record CampAction() : EventCode;
    public record ChestAction() : EventCode;
    public record EventAction() : EventCode;
}

// Model definition for `abyss_x::models::message::MessageEvent` model
public class MessageEvent : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("event_code")]
    public EventCode event_code;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }

    public override void OnUpdate(Model model)
    {
        base.OnUpdate(model);
        Debug.LogError(123213213232);
    }
}
        