// Generated by dojo-bindgen on Fri, 21 Jun 2024 11:07:27 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Dojo.Torii;
using UnityEngine;
using Utils;
using Enum = Dojo.Starknet.Enum;

// Type definition for `core::byte_array::ByteArray` struct
[Serializable]
// public struct ByteArray {
//     public string[] data;
//     public FieldElement pending_word;
//     public uint pending_word_len;
// }

// Type definition for `abyss_x::utils::constant::EventCode` enum
public abstract record EventCode() : Enum {
    public record None() : EventCode;
    public record Login() : EventCode;
    public record SetNickName() : EventCode;
    public record StartGame() : EventCode;
    public record GiveUpGame() : EventCode;
    public record SelectRoad() : EventCode;
    public record CheckBattleResult() : EventCode;
    public record ChooseEventBonus() : EventCode;
    public record CampAction() : EventCode;
    public record ChestAction() : EventCode;
    public record EventAction() : EventCode;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}


// Model definition for `abyss_x::models::opt::Opt` model
public class Opt : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("code")]
    public EventCode code;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update()
    {
        this.AnylyseOpt();
    }

    public override void OnUpdate(Model model)
    {
        base.OnUpdate(model);
        Debug.LogError("Opt Update to ");
        this.AnylyseOpt();
        this.InformOpt();
        
    }
}
        