// Generated by dojo-bindgen on Fri, 21 Jun 2024 11:07:27 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.CompilerServices.Events;
using Dojo.Torii;
using GameCore;
using Enum = Dojo.Starknet.Enum;


// Model definition for `abyss_x::models::role::Role` model
    public class Role : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("cur_stage")]
        public byte cur_stage;

        [ModelField("selected_road")]
        public byte selected_road;

        [ModelField("hp")]
        public ushort hp;

        [ModelField("max_hp")]
        public ushort max_hp;

        [ModelField("talent")]
        public ushort talent;

        [ModelField("blessing")]
        public uint blessing;

        [ModelField("relic")]
        public ulong relic;

        [ModelField("seed")]
        public ulong seed;

        public override void OnUpdate(Model model)
        {
            base.OnUpdate(model);
            var eventArg = DojoRoleUpdate.Create(
                this.cur_stage,
                this.selected_road,
                this.hp,
                this.max_hp,
                this.talent,
                this.blessing,
                this.seed);
            Entry.Event.Fire(DojoRoleUpdate.EventId, eventArg);
        }
    }
        