// Generated by dojo-bindgen on Tue, 18 Jun 2024 07:35:41 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `core::byte_array::ByteArray` struct
[Serializable]
public struct ByteArray {
    public string[] data;
    public FieldElement pending_word;
    public uint pending_word_len;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}


// Model definition for `abyss_x::models::role::Role` model
public class Role : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("cur_stage")]
    public byte cur_stage;

    [ModelField("hp")]
    public ushort hp;

    [ModelField("max_hp")]
    public ushort max_hp;

    [ModelField("talent")]
    public ushort talent;

    [ModelField("blessing")]
    public uint blessing;

    [ModelField("relic")]
    public ulong relic;

    [ModelField("seed")]
    public ulong seed;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        