// Generated by dojo-bindgen on Fri, 21 Jun 2024 11:07:27 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Dojo.Torii;
using UnityGameFramework.Runtime;
using Enum = Dojo.Starknet.Enum;


// Model definition for `abyss_x::models::user::User` model
public class User : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("state")]
    public byte state;

    [ModelField("game_mode")]
    public byte game_mode;

    [ModelField("role_category")]
    public byte role_category;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }

    public override void OnUpdate(Model model)
    {
        base.OnUpdate(model);
        Log.Warning("User Sync => " + this.state);
    }
}
        